### ISSUE TITLE
The .ipa file appears to be treated as text.

### ISSUE THREAD

**Issue by swpalmer** [anki-community/vector-archive#2]
The .ipa file appears to be treated as text.  Raw file shows 3 lines of text for a 111MB file.  How do you download the full thing?

**Comment by markustenghamn** [comment]
You can right click and click "Save Link As..." in most browsers ![https://i.gyazo.com/4681ea38946d7641097bbb6ae1516fb8.gif](https://i.gyazo.com/4681ea38946d7641097bbb6ae1516fb8.gif)

Or just copy the link and use something like `wget https://github.com/anki-community/vector-archive/blob/master/applications/Vector%20Robot_1.5.0.ipa` in your terminal.

**Comment by remona-minett** [comment]
appears to be solved, can this be closed
