### ISSUE TITLE
Update OTA

### ISSUE THREAD

**Issue by picpic2b** [anki-community/vector-archive#3]
Hello , some one can tell me how to uptade vector with the ota ? thx a lot

**Comment by kercre123** [comment]
Do you mean you want to update Vector with the OTA that is uploaded here? You can do that with BLE or DNS redirection, but this OTA is the latest one and has no changes to it.

**Comment by remona-minett** [comment]
Vector updates on his own from the cloud servers. As far as I know we haven't gotten to the point of making our own custom updates.

**Comment by rmcolbert** [comment]
As @remona-minett mentioned, we have not made it to a point where we can produce custom updates, it is possible to downgrade Vector to his base firmware and then using DNS redirection force him to load a different OTA update version. He does; however, have downgrade protection so you have to start from a factory reset Vector.
